version: '3.9'

services:
    climate-db:
        container_name: climate-db
        image: postgres:15
        env_file: 
            - ./.env
        ports:
            - 5433:5432
        volumes:
            - climate-db-data:/var/lib/postgresql/data
            # - ./db/postgres.conf:/etc/postgresql/postgresql.conf
            # - ./db/data:/data

        # command: postgres -c config_file=/etc/postgresql/postgresql.conf
        restart: on-failure
        healthcheck:
            test: "exit 0"

volumes:
    climate-db-data:
